// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhbeklqgcmfqbvywvrxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYmVrbHFnY21mcWJ2eXd2cnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDY1ODIsImV4cCI6MjA4NTg4MjU4Mn0.0Z90ZAXF6wmzx93hX5rl_68GPYiZ3fEHREQhxwpiEzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});